name: Cleanup Workflow Runs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  delete_old_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write

    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2.0.6
        with:
          token: ${{ secrets.ACTIONS_PAT }}
          repository: ${{ github.repository }}
          retain_days: 30