# Github action to build Docker image from main branch (tag: latest)

name: Build Docker Image (main)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (main)
        uses: actions/checkout@v2.3.4
        with:
          repository: 'dontobi/motioneye.rpi'
          ref: 'main'

      - name: Get and write version
        id: version
        run: |
          VERSION="$(cat .VERSION)"
          DATI="$(date --rfc-3339=seconds | sed 's/ /T/')"
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "dati=$DATI" >> $GITHUB_ENV
          sed -e "s/\${VERSION}/$VERSION/" -e "s/\${DATI}/$DATI/" ./Dockerfile > ./Dockerfile.tmp
          mv -f ./Dockerfile.tmp ./Dockerfile

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.5.1

      - name: Login to DockerHub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build Docker image (arm32v7)
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/arm/v7
          tags: |
            dontobi/motioneye.rpi:${{ env.version }}-arm32v7,
            dontobi/motioneye.rpi:latest