# Github action to build Docker image from main branch (tag: latest)

name: Build Docker Image (main)

on:
  workflow_dispatch:
  release:
    types:
      - published
  schedule:
    - cron:  '0 0 * * FRI'

jobs:
  bulid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (main)
        uses: actions/checkout@v2.4.0
        with:
          repository: 'dontobi/motioneye.rpi'
          ref: 'main'

      - name: Get and write version
        id: version
        run: |
          VERSION="$(cat .VERSION)"
          DATI="$(date --rfc-3339=seconds | sed 's/ /T/')"
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "dati=$DATI" >> $GITHUB_ENV
          sed -e "s/\${VERSION}/$VERSION/" -e "s/\${DATI}/$DATI/" ./Dockerfile > ./Dockerfile.tmp
          mv -f ./Dockerfile.tmp ./Dockerfile

      - name: Set up manifest tool
        run: |
          wget https://github.com/estesp/manifest-tool/releases/download/v1.0.3/manifest-tool-linux-amd64 -O manifest-tool
          chmod +x manifest-tool

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to DockerHub
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build Docker image
        uses: docker/build-push-action@v2.8.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/arm/v7,linux/arm64
          tags: |
            dontobi/motioneye.rpi:${{ env.version }},
            dontobi/motioneye.rpi:latest
